name: shared
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
dependencies:
  app_ui:
    path: ../app_ui
  blurhash: ^1.1.1
  dio: ^5.7.0
  env:
    path: ../env
  flutter_image_compress: ^2.3.0
  freezed_annotation: ^2.4.4
  http_parser: ^4.0.2
  image_picker_plus:
    path: ../image_picker_plus
  intl: ^0.19.0

  logger: ^2.4.0
  meta: ^1.15.0
  mime: ^1.0.6
  powersync: ^1.5.3
  user_repository: 
    path: ../user_repository
  video_compress: ^3.1.3
