name: user_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  database_client:
    path: /Users/yazilimasrra/demoProject/flutter_instagram_clone/flutter_instagram_clone/packages/database_client
  powersync_repository:
    path: ../powersync_repository
  rxdart: ^0.28.0
  shared:
    path: ../shared
