// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjnuQTo5zXd_qULYiqB-fbempwpj7AHW4',
    appId: '1:66115683621:android:9bc6fa826e921de730c6cc',
    messagingSenderId: '66115683621',
    projectId: 'flutter-instagram-clone-2635a',
    storageBucket: 'flutter-instagram-clone-2635a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzsC5NO1x2E-IU810E7ygJNY358_lbzMI',
    appId: '1:66115683621:ios:f8764a95daf498f730c6cc',
    messagingSenderId: '66115683621',
    projectId: 'flutter-instagram-clone-2635a',
    storageBucket: 'flutter-instagram-clone-2635a.appspot.com',
    androidClientId: '66115683621-8ggbd2kq0hn27nqr7st50l0511e0nk2l.apps.googleusercontent.com',
    iosClientId: '66115683621-6a5qh3re51ev45uhkt4p9p3sl4fir8mb.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.flutter-instagram-clone.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzsC5NO1x2E-IU810E7ygJNY358_lbzMI',
    appId: '1:66115683621:ios:f8764a95daf498f730c6cc',
    messagingSenderId: '66115683621',
    projectId: 'flutter-instagram-clone-2635a',
    storageBucket: 'flutter-instagram-clone-2635a.appspot.com',
    androidClientId: '66115683621-8ggbd2kq0hn27nqr7st50l0511e0nk2l.apps.googleusercontent.com',
    iosClientId: '66115683621-6a5qh3re51ev45uhkt4p9p3sl4fir8mb.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.flutter-instagram-clone.stg',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6fAuC_n3P59o2c_ZvTHITAR3RzTsGFLo',
    appId: '1:66115683621:web:9a25a4e0ad38e7d930c6cc',
    messagingSenderId: '66115683621',
    projectId: 'flutter-instagram-clone-2635a',
    authDomain: 'flutter-instagram-clone-2635a.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-2635a.appspot.com',
  );

}