// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqy7VEZpI96lJ9X4R4ok_LvhRCtynLkUg',
    appId: '1:127666790716:android:2751a01ffb2176f94a7e39',
    messagingSenderId: '127666790716',
    projectId: 'flutter-instagram-clone-5e201',
    storageBucket: 'flutter-instagram-clone-5e201.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkVXeB3tF7J1K5L0t7FJq4jQzOj_rIRQ8',
    appId: '1:127666790716:ios:749dbd52259ed48f4a7e39',
    messagingSenderId: '127666790716',
    projectId: 'flutter-instagram-clone-5e201',
    storageBucket: 'flutter-instagram-clone-5e201.appspot.com',
    androidClientId: '127666790716-7u8h0csd0hnq0sj0noacbb4pv9v3vlp7.apps.googleusercontent.com',
    iosClientId: '127666790716-to5sntoca7ev4ccp35un9qpkgu37i2tr.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.flutter-instagram-clone.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkVXeB3tF7J1K5L0t7FJq4jQzOj_rIRQ8',
    appId: '1:127666790716:ios:749dbd52259ed48f4a7e39',
    messagingSenderId: '127666790716',
    projectId: 'flutter-instagram-clone-5e201',
    storageBucket: 'flutter-instagram-clone-5e201.appspot.com',
    androidClientId: '127666790716-7u8h0csd0hnq0sj0noacbb4pv9v3vlp7.apps.googleusercontent.com',
    iosClientId: '127666790716-to5sntoca7ev4ccp35un9qpkgu37i2tr.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.flutter-instagram-clone.dev',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOZV5pWz5wELeSVoqorx2VvfwEY6fW5fs',
    appId: '1:127666790716:web:4802cf1274e921ef4a7e39',
    messagingSenderId: '127666790716',
    projectId: 'flutter-instagram-clone-5e201',
    authDomain: 'flutter-instagram-clone-5e201.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-5e201.appspot.com',
  );

}