// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJFjmTDabziAG_drFRnu3Fdyhy3VwNZDc',
    appId: '1:929256685723:android:3fea27b60631616461c63e',
    messagingSenderId: '929256685723',
    projectId: 'flutter-instagram-clone-cbe6d',
    storageBucket: 'flutter-instagram-clone-cbe6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEBpSgg5QSlJ1FiqpoAOI4voTZ3HWNd3I',
    appId: '1:929256685723:ios:b6ca59fdecada30e61c63e',
    messagingSenderId: '929256685723',
    projectId: 'flutter-instagram-clone-cbe6d',
    storageBucket: 'flutter-instagram-clone-cbe6d.appspot.com',
    androidClientId: '929256685723-9tibos6a3puo88n37d736f1c5j9vcpi4.apps.googleusercontent.com',
    iosClientId: '929256685723-87ga10p9f9c06tg2vpfhkk7rg1hjoha3.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.flutter-instagram-clone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEBpSgg5QSlJ1FiqpoAOI4voTZ3HWNd3I',
    appId: '1:929256685723:ios:b6ca59fdecada30e61c63e',
    messagingSenderId: '929256685723',
    projectId: 'flutter-instagram-clone-cbe6d',
    storageBucket: 'flutter-instagram-clone-cbe6d.appspot.com',
    androidClientId: '929256685723-9tibos6a3puo88n37d736f1c5j9vcpi4.apps.googleusercontent.com',
    iosClientId: '929256685723-87ga10p9f9c06tg2vpfhkk7rg1hjoha3.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.flutter-instagram-clone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFifZxBvVfVp13SPvUcTuAFj5sYAv_iqE',
    appId: '1:929256685723:web:5ee339bae684024d61c63e',
    messagingSenderId: '929256685723',
    projectId: 'flutter-instagram-clone-cbe6d',
    authDomain: 'flutter-instagram-clone-cbe6d.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-cbe6d.appspot.com',
  );

}